# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dist_mr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dist_mr.proto',
  package='count_wordula',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdist_mr.proto\x12\rcount_wordula\"8\n\x0cWorkerStatus\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x15\n\rworker_status\x18\x02 \x01(\x05\"\x7f\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x11\n\ttask_type\x18\x02 \x01(\x05\x12\x11\n\tinput_dir\x18\x03 \x01(\t\x12\x16\n\x0einput_filename\x18\x04 \x01(\t\x12\x12\n\noutput_dir\x18\x05 \x01(\t\x12\t\n\x01N\x18\x06 \x01(\x05\x12\t\n\x01M\x18\x07 \x01(\x05\"`\n\x0c\x45xecutedTask\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x11\n\ttask_type\x18\x02 \x01(\x05\x12\x17\n\x0foutput_filename\x18\x03 \x01(\t\x12\x13\n\x0btask_status\x18\x04 \x01(\x05\x32P\n\x0fMapReduceDriver\x12=\n\x07GetTask\x12\x1b.count_wordula.WorkerStatus\x1a\x13.count_wordula.Task\"\x00\x62\x06proto3'
)




_WORKERSTATUS = _descriptor.Descriptor(
  name='WorkerStatus',
  full_name='count_wordula.WorkerStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='count_wordula.WorkerStatus.worker_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_status', full_name='count_wordula.WorkerStatus.worker_status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=88,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='count_wordula.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='count_wordula.Task.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_type', full_name='count_wordula.Task.task_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_dir', full_name='count_wordula.Task.input_dir', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_filename', full_name='count_wordula.Task.input_filename', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_dir', full_name='count_wordula.Task.output_dir', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='N', full_name='count_wordula.Task.N', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='M', full_name='count_wordula.Task.M', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=217,
)


_EXECUTEDTASK = _descriptor.Descriptor(
  name='ExecutedTask',
  full_name='count_wordula.ExecutedTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='count_wordula.ExecutedTask.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_type', full_name='count_wordula.ExecutedTask.task_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_filename', full_name='count_wordula.ExecutedTask.output_filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_status', full_name='count_wordula.ExecutedTask.task_status', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=315,
)

DESCRIPTOR.message_types_by_name['WorkerStatus'] = _WORKERSTATUS
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['ExecutedTask'] = _EXECUTEDTASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkerStatus = _reflection.GeneratedProtocolMessageType('WorkerStatus', (_message.Message,), {
  'DESCRIPTOR' : _WORKERSTATUS,
  '__module__' : 'dist_mr_pb2'
  # @@protoc_insertion_point(class_scope:count_wordula.WorkerStatus)
  })
_sym_db.RegisterMessage(WorkerStatus)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'dist_mr_pb2'
  # @@protoc_insertion_point(class_scope:count_wordula.Task)
  })
_sym_db.RegisterMessage(Task)

ExecutedTask = _reflection.GeneratedProtocolMessageType('ExecutedTask', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEDTASK,
  '__module__' : 'dist_mr_pb2'
  # @@protoc_insertion_point(class_scope:count_wordula.ExecutedTask)
  })
_sym_db.RegisterMessage(ExecutedTask)



_MAPREDUCEDRIVER = _descriptor.ServiceDescriptor(
  name='MapReduceDriver',
  full_name='count_wordula.MapReduceDriver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=317,
  serialized_end=397,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTask',
    full_name='count_wordula.MapReduceDriver.GetTask',
    index=0,
    containing_service=None,
    input_type=_WORKERSTATUS,
    output_type=_TASK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAPREDUCEDRIVER)

DESCRIPTOR.services_by_name['MapReduceDriver'] = _MAPREDUCEDRIVER

# @@protoc_insertion_point(module_scope)
